# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Wf1Job1:
    # The type of runner that the job will run on
    uses: nabajit00/workflow_reusuable/.github/workflows/reuse.yml@main
    with:
      who: "WF1"
